### ISSUE TITLE
[UPDATER] Always ask to update

### ISSUE THREAD

**Issue by TheSoraHD** [TopazTK/KH-ReFixed#10]
![image](https://user-images.githubusercontent.com/8531824/155423613-7ac8becf-a5e6-432b-bd0f-3b1d06191e78.png)

**Comment by TopazTK** [comment]
This is what I have feared would happen. You see:
Difference of culture, you do not use the same decimal splitter as the US does.
This should be an easy fix, will address shortly.

**Comment by TopazTK** [comment]
Yup! The version is reported correctly on my end.
This should be fixed at once.
![image](https://user-images.githubusercontent.com/95656963/155426372-291f6516-6fff-42be-a9be-8835662e58d8.png)

**Comment by TopazTK** [comment]
Should be fixed with 95ced98d1742235e07030852ac168478407eeca2.
Tests are necessary. Closing for now.
