### ISSUE TITLE
[BUG] KH2 - Limit form text flicker

### ISSUE THREAD

**Issue by Fivavoa** [TopazTK/KH-ReFixed#12]
**Re:Fixed Version:**
1.50
**Game in Question:**
Kingdom Hearts II
**Bug Description:**
For some reason, the text flickers during the shortcut menu of Limit Form. To be fair, I used the KHPatcher thing and I'm not sure if that's an exe mod at all, but I figured I'd ask in here just in case. All I've added was HD textures and the PS2 music mods. (If it is an exe edit, let me know and sorry for wasting your time!)
**Screenshots/Video:**

![untitled](https://user-images.githubusercontent.com/29827600/155709729-69c3e223-d9d4-4c21-a9e6-e279d38d708f.GIF)

**Comment by TopazTK** [comment]
Okay so, do you have X or O to confirm?

**Comment by TopazTK** [comment]
Turns out that dnSpy misinterpreted some code, fixed with 994d592fa418a0f3829fed44e78415d364e5eaad.
Closing...

**Comment by Fivavoa** [comment]
Sorry for the late reply! If it helps, I had X to confirm. Otherwise, thank you for all your hard work!
