### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by HereAtLast1** [TopazTK/KH-ReFixed#148]
the "mod.yml" file and wont let me download without it

**Comment by KHOmega** [comment]
You completely glossed over the instructions on how to install the mod.

As referred to on the main page:

## Download

Get the latest release by clicking the button below.

[![KH-ReFixed](https://img.shields.io/badge/Kingdom_Hearts_Re:Fined-Download-blue.svg)](https://github.com/TopazTK/KH-ReFined/releases)

### Installation

Installing Re:Fined is easy, even though it may seem like a monumential task. Please refer to [this page](SETUP.md) for full instructions.

If you're installing a pre-v4.xx version of Re:Fined, simply extract the archive into the folder with your game and rename the exe's to the vanilla names. Support for them is not provided per https://github.com/KH-ReFined/KH-ReFined/issues/117.
