### ISSUE TITLE
Document build procedure

### ISSUE THREAD

**Issue by tryashtar** [TopazTK/KH-ReFixed#149]
Hi, welcome back. I would appreciate if comprehensive instructions for building this project could be added. This would make it possible to independently test issues, make contributions, and create forks. Without a build procedure, this codebase is not meaningfully open source. Thanks for your time and effort.

**Comment by TopazTK** [comment]
Will be done. Th eprocess is devilishly complicated, so time is needed.
Closing.

**Comment by tryashtar** [comment]
Thank you. Please keep me updated :)
