### ISSUE TITLE
[BUG] Limit Form Shortcuts Swapping

### ISSUE THREAD

**Issue by Truthful-Sentiment** [TopazTK/KH-ReFixed#15]
Re:Fixed Version: v1.50

Game in Question: Kingdom Hearts II Final Mix (1.0.0.8)

Bug Description: If Confirm is set to X/A, activating Limit Form and opening the Shortcuts menu shows Ragnarok and Sonic Blade swapping quickly between X/A and O/B. Both text and functionality swaps, so pushing the same button multiple times can trigger either attack if timed. Setting Confirm to O/B does not have this effect.

Reproduction Steps: Activate Limit Form and hold L1/LB to access the Shortcuts menu. Confirm is set to X.

**Comment by TopazTK** [comment]
Please look at the closed issues before opening a new one.
This was fixed in the upcoming v2.00 version.
