### ISSUE TITLE
[BUG] Hades Escape mission restarts upon completing it after selecting "Retry"

### ISSUE THREAD

**Issue by xlash123** [TopazTK/KH-ReFixed#150]
**Re:Fined Version:**
v4.20 - STABLE

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
During the Hades Escape mission, upon dying and selecting retry, the completion of the Hades Escape mission immediately places the party back at the beginning of the sequence, as if I had failed and retried.

I do not know if completing it a second time will allow for continuation of the story, but selecting "Continue" instead of "Retry" does allow for the story to continue after completing Hades Escape.

**Reproduction Steps:**
1. Start the Hades Escape mission
2. Die
3. Select "Retry"
4. Complete the Hades Escape mission

**Comment by TopazTK** [comment]
Fixed in v4.30. Closing.
