### ISSUE TITLE
[BUG] Story Roxas fight does not have the "Retry" or "Prepare and Retry" options upon dying

### ISSUE THREAD

**Issue by xlash123** [TopazTK/KH-ReFixed#151]
**Re:Fined Version:**
v4.20 - STABLE

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
When doing the story Roxas fight (not data), dying to Roxas gives the vanilla death screen and not the one with the "Retry" and "Prepare and Retry" options.

**Reproduction Steps:**
1. Enter the story Roxas fight
2. Die

**Comment by xlash123** [comment]
The same bug also occurs with the first story Xemnas fight.

**Comment by TopazTK** [comment]
Fixed as of v5.00 - Xemnas is intentional as final fights do have retrying.
Closing.
