### ISSUE TITLE
NO Logo(s) ho-to

### ISSUE THREAD

**Issue by Klemci** [TopazTK/KH-ReFixed#153]
### What Re:Fined version are you using? (versions other than listed are not supported)

v3.15

### Was the issue non-existant in some previous version?

for 5.0 too

### In which game is the bug happening?

Kingdom Hearts I Final Mix

### The bug & it's reproduction steps

All 4 games !!!!

I applied NOLogo for each "vanilla" game (LuaBackend Hook), how could i use it working for refined ?

[logo scripts and empty refined folder.zip](https://github.com/KH-ReFined/KH-ReFined/files/14040650/logo.scripts.and.empty.refined.folder.zip)

### What should've hapepned instead

Logos could be skipped

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by Klemci** [comment]
Well, i renamed the EXEs "_refined", i see the lua loader .toml has EXE name listed.... crap

Edit:
no luck

**Comment by TopazTK** [comment]
External mods get no support.
Closing.
