### ISSUE TITLE
Constant stuttering after updating to v5.00

### ISSUE THREAD

**Issue by jinglebuns** [TopazTK/KH-ReFixed#154]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest v4.xx

### Was the issue non-existant in some previous version?

v4.20

### In which game is the bug happening?

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

Updating to v5.00 has introduced constant stuttering and poor performance for me:
![Video](https://github.com/KH-ReFined/KH-ReFined/assets/16826472/39ea6e10-6bb9-4566-8821-c9637d425669)

Happens on the title screen, and pre-rendered cutscenes as well.

![image](https://github.com/KH-ReFined/KH-ReFined/assets/16826472/fd5de12e-3aa5-438b-aa23-3d5a0de3f420)

Also your discord link is broken :(

### What should've hapepned instead

smooth video game

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Fixed with the hotfix. Please use that instead.
Closing.
