### ISSUE TITLE
Can't open the tool. EOSSDK-Win64-Shipping.dll missing (VC ++ rdy)

### ISSUE THREAD

**Issue by RealSankiri** [TopazTK/KH-ReFixed#157]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

Hi, 

I try install vc ++ but din't help. https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

What should i do? (I did restart + reinstall again (unsitall firtst restart then install))

(Program don't start)

see ya 

### What should've hapepned instead

![image](https://github.com/KH-ReFined/KH-ReFined/assets/101787349/a47f96f4-bf9d-4c3d-b107-cf948cfc2517)

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Put the EXE where it's supposed to. If you have done so, reinstall the game.
The said DLL comes with the game itself.
Closing.
