### ISSUE TITLE
Option to revert save file relocation in preparation for Steam version

### ISSUE THREAD

**Issue by Dinjoralo** [TopazTK/KH-ReFixed#158]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts I Final Mix

### The bug & it's reproduction steps

As you've no doubt heard, Steam versions for both the Kingdom Hearts compilations have been announced. On the store pages for both, they are listed as having support for Steam Cloud Saves;

https://store.steampowered.com/app/2552430/KINGDOM_HEARTS_HD_1525_ReMIX/
https://store.steampowered.com/app/2552440/KINGDOM_HEARTS_HD_28_Final_Chapter_Prologue/

Cloud saves will only work properly if the save file is where the game normally places it. So, it will be important to have the means of undoing Re:Fined's changes to how save and config files are handled. 

### What should've hapepned instead

N/A

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Re:Fined will not move the save files on Steam should they have Cloud support.
Chances are that info is wrong and they will not.
But if they do, it would be based, and they will be at their own place in Steam.
Closing as "Accepted"

**Comment by Dinjoralo** [comment]
Heads up, the collections do in fact have proper cloud saves on Steam. The saves are actually in different locations, tucked in the "My Games" folder in Documents.
