### ISSUE TITLE
German Voice Over kills GoA

### ISSUE THREAD

**Issue by ZeitHeld** [TopazTK/KH-ReFixed#159]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

These Mods are activated (Rando uses the Starter Preset):
![image](https://github.com/KH-ReFined/KH-ReFined/assets/76132257/966681d6-143a-4e30-abbb-c7f060fbddb7)

When I enter the Garden of Assembley with German VO, and then interact with the computer, my game crashes once the the cutscene ends. (chests look like vanilla)
When I start the game in english, everything works fine, and so does switching to Japanese. But when I switch to german, it crashes instantly
I don't know if the audio handler thing causes that issue somehow, or if there are just missing things in the german VO or something

It just seems so strange to me, not sure if you can fix it though. I mean, the room itself is working, just once the portals are spawned

EDIT:
The Randomizer is not the cause, with it deactivated it remains the same
The GoA mod however seems to be the culprit

### What should've hapepned instead

I would see the Garden of Assembley with their custom world icons, being able to move around

### Logs

No Log exists

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
I will look into this.

**Comment by TopazTK** [comment]
Closed due to overhaul of the mod. Please remake the issue if it persists through the re-release.
