### ISSUE TITLE
Encounter Plus ability does not show Triangle/Y prompt in ability menu.

### ISSUE THREAD

**Issue by BigBandy** [TopazTK/KH-ReFixed#160]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

Pretty self-explanatory.
![image](https://github.com/KH-ReFined/KH-ReFined/assets/51020735/d821eade-152f-49a1-91c7-59fff6d3a3fa)

### What should've hapepned instead

Triangle prompt should be displayed to left of ability.

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
You are using another mod that is causing a clash. No support will be provided.
Closing.
