### ISSUE TITLE
[Bug]: Softlocking Atlantica when using auto-save file

### ISSUE THREAD

**Issue by yxrei** [TopazTK/KH-ReFixed#161]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

When entering the first musical (and you soft reset the game, that's how it happened for me but it's not needed to reproduce, quitting the game will most likely also work since it's about the auto-save), you then use the auto-save, **all NPC's are gone**, making it impossible to start the musical again. Going to the World Map and back to Atlantica doesn't change it.

I'm not sure if it would fix itself after Atlantica gets a new chapter added as it _just_ happened in my playthrough but can update it once I get to that point.

Save file (Slot 99):  
![KHIIFM](https://github.com/KH-ReFined/KH-ReFined/assets/28786333/7801d78c-4c71-4641-8bd1-2e616729f495)

(I hope it's the right save file but it should be, if Slot 99 isn't the correct one then I'll update it aswell.)

### What should've hapepned instead

The NPC's should be there to (re)start the musical.

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Closed due to overhaul of the mod. Please remake the issue if it persists through the re-release.
