### ISSUE TITLE
Sora has bronze crown since getting new clothes and face texture not changing during animations

### ISSUE THREAD

**Issue by DrYima** [TopazTK/KH-ReFixed#163]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### Was the issue non-existant in some previous version?

No clue

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

Sora has the bronze crown on his model as soon as he gained his new clothes from the fairies.
![image_2024-06-28_123605874](https://github.com/KH-ReFined/KH-ReFined/assets/92368255/4029a23e-ef30-400d-bc14-de20f0c730b8)

Most of the time, character's faces don't change at all, but instead glitch out when they are suppose to open their mouth and such, both in and out of cutscenes.
![image_2024-06-28_130508530](https://github.com/KH-ReFined/KH-ReFined/assets/92368255/38bfde26-6020-4c8f-9663-d390fc066e68), 
![image_2024-06-28_131048696](https://github.com/KH-ReFined/KH-ReFined/assets/92368255/c9d65045-1f36-461c-95ba-4990775a094d)

### What should've happened instead

I don't have any of the proofs to gain the crown so I shouldn't have the crown

Characters are supposed to emote more

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Re:Fined is incompatbile with the latest releases. Please do not use it until an update is given.
Closing.
