### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by Flaming59** [TopazTK/KH-ReFixed#164]
### What Re:Fined version are you using? (versions other than listed are not supported)

v4.75

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts 2 Final Mix

### The bug & it's reproduction steps

the first issue is when i install Kingdom hearts 2 Re:Find it seems like a file is missing from it. item-360.dds. 

for the 2nd reason the Spanish vo doesn't work. 

for the 3rd reason. i couldn't find anything on this so i'm putting it here. i can't use any lua files.

### What should've hapepned instead

for the first issue t doesn't seem to do anything but since it says there's supposed to be a file there i assume i need it for something

for the second issue i installed it correctly. but it says there's A LOT of files missing. personally i don't want to use it but it's still a problem

 i wanna use lua files but it seems like when i install this mod it doesn't work. so idk what to do. if it doesn't work with lua files then i feel like it should say on the description. but i would like for it to be. since there's mods i want like the "show struggle weapons in inventory" mod

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Closed due to overhaul of the mod. Please remake the issue if it persists through the re-release.
