### ISSUE TITLE
Sora name showing as FAKE in menu, along with some config options

### ISSUE THREAD

**Issue by MLamb14** [TopazTK/KH-ReFixed#165]
### What Re:Fined version are you using? (versions other than listed are not supported)

Latest release

### In which game is the bug happening?  (games other than listed are not supported)

Kingdom Hearts II Final Mix

### The bug & it's reproduction steps

Per title, Sora's name shows as FAKE in the menu and a couple of config options are listed as fake. Didn't notice either until the latest release, which I auto-updated to in game when prompted.

![20241223205021_1](https://github.com/user-attachments/assets/2d182383-10b2-4ad1-b54d-50ac78782daa)

![20241223205047_1](https://github.com/user-attachments/assets/9bf0e9bc-622a-4056-ba98-f61146661dab)

### What should've hapepned instead

Sora's name should appear as normal

### I did the following:

- [X] Make sure the Re:Fined .exe and OpenKH are up-to-date.
- [X] [See if the issue has been mentioned before](https://github.com/KH-ReFined/KH-ReFined/issues).

**Comment by TopazTK** [comment]
Please update the MAIN mod through OpenKH!
Closing.
