### ISSUE TITLE
Conflict with Text Editing Mods

### ISSUE THREAD

**Issue by Naxshe** [TopazTK/KH-ReFixed#17]
**Re:Fixed Version:**
[v1.50]

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Messes with the text when you have text based mods in effect

**Reproduction Steps:**
the way i did it is install my roxas mod which edits the text and such
as a result various things displayed the wrong text

**Screenshots/Video:**
[https://puu.sh/IN9Aw/cc5a9df303.png](url)

**Comment by TopazTK** [comment]
Fixed regardless in v2.50. Closing.
