### ISSUE TITLE
[BUG] Can't use Situation Command

### ISSUE THREAD

**Issue by EmreXCoded** [TopazTK/KH-ReFixed#20]
**Re:Fixed Version:** v2.10 (1.0.1.8 EXE)

**Game in Question:** Kingdom Hearts II

**Bug Description:** Can not use Situation Command, unable to proceed in Story

**Reproduction Steps:** 
1. Start a new game
2. Select Skip Tutorial
3. Button Prompt does not appear

**Screenshots/Video:** 
![image](https://user-images.githubusercontent.com/40892993/157038759-a843e0ae-e276-4535-a99a-bdac2eadfc3d.png)

**Comment by EmreXCoded** [comment]
Extra Info: I'm NOT Using the Dual Audio Mod. I did not patch the Game with it.

**Comment by EmreXCoded** [comment]
Extra Info 2: The Bug is not fixed even WITH Dual Audio installed.

**Comment by EmreXCoded** [comment]
Extra Info 3: I tried the 1.0.0.8 EXE (the NOT DA Build) and now Situation Command works + The Text is not bugged anymore. Looking forward to a fix for the DA Build EXE

**Comment by TopazTK** [comment]
Thanks for the report! A hotfix has been released fixing this issue.
Please re-download all v1.0.0.8 releases.
Closing.
