### ISSUE TITLE
[BUG] Limit Form's Rave showing up incorrectly in other languages than English

### ISSUE THREAD

**Issue by TheSoraHD** [TopazTK/KH-ReFixed#22]
**Re:Fixed Version:**
_v2.10_

**Game in Question:**
_Kingdom Hearts II_

**Bug Description:**
_Limit Form's Rave and its first RC (End) shows up in English instead of Spanish. Everything else related to Limit Form is fine._

**Reproduction Steps:**
_Open the game in Spanish. Enter Limit Form in a battle._

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/8531824/157317840-30ce8b73-2d73-4200-aa2c-a6365b1c6377.png)

**Comment by TopazTK** [comment]
Only English is supported. #16 wants to solve this issue.
Closing.
