### ISSUE TITLE
[FEATURE REQUEST] KHII: Dynamic Ultrawide Support

### ISSUE THREAD

**Issue by TheSoraHD** [TopazTK/KH-ReFixed#23]
It would be nice to have Ultrawide for KH2 implemented in Re:Fixed. For reference, this Lua mod works like a charm: [Dynamic Ultrawide Support](https://www.nexusmods.com/kingdomhearts2finalmix/mods/77)

**Comment by TopazTK** [comment]
Talked to the guy and got the permission AFTER 2.10
It will be in the 2.20 release.

**Comment by TopazTK** [comment]
Closing temporarily. KH2 is weird and it's aspect ratio fix does not affect 2D elements.
I will do some optional but highly recommended SEQD fixes for the menus as best as I can.
Until then, this is closed.

**Comment by JarekToro** [comment]
How is this coming?

**Comment by TopazTK** [comment]
Not coming. KH2 Menus are fucked in Ultrawide. Closed until it can be addressed.

**Comment by JarekToro** [comment]
I'm a software engineer myself. Not a game dev by any means but I know my way around c# is there a branch I can mess with?

**Comment by TopazTK** [comment]
> I'm a software engineer myself. Not a game dev by any means but I know my way around c# is there a branch I can mess with?

This is not an issue about C# or ASM, it's about the LAYD and SEQD files within KH2, which unlike KH1, do not accommodate the frame that they are stretched to.

I'd have to go and make ultrawide compliant versions of ALL 2D files in the game. I won't do this yet.
But if YOU wanna, go ahead and fork this and make a PR when you are done.

**Comment by JarekToro** [comment]
Thanks for the info. I'll see what I can do.
