### ISSUE TITLE
KH1 - Ultrawide Fix Not Working

### ISSUE THREAD

**Issue by toeofjesus** [TopazTK/KH-ReFixed#26]
Having trouble with ultrawide using ReFixed 2.10. So far, have used all available .exe's from the ReFixed v2.10 zip file for Kingdom hearts 1. Have made sure my game is set to fullscreen with the correct resolution (3440 x 1440). There are still black bars on left and right of screen using this mod.  I have tried the following:
 -Kingdom Hearts - Final Mix v1.0.0.0
-Kingdom Hearts - Final Mix v1.0.0.2
-Kingdom Hearts - Final Mix v1.0.1.0
-Kingdom Hearts - Final Mix v1.0.1.2
My monitor is 21:9 3440x1440.

**Comment by epic-bruh-moment** [comment]
I have heard that the next version of the mod will have dynamic ultrawide baked into it, so its best to wait for the next update.

**Comment by TopazTK** [comment]
KH1 has Dynamic Ultrawide baked into it and it should be functional.
Please show me some screenshots, a video would be better.

**Comment by toeofjesus** [comment]
Sorry I refunded the game. The only way I could get widescreen to work is by using this: https://www.nexusmods.com/kingdomheartsfinalmix/mods/51

It's got two side bars on both sides of the screen like its 16:9 aspect ratio. Your mod was working outside of that because I could see the enhanced settings.

**Comment by TopazTK** [comment]
Closing, as no one was able to reproduce this.
Will re-open once reproduced.
