### ISSUE TITLE
[BUG] Infinite Loading Times (2.10)

### ISSUE THREAD

**Issue by Cuddlecreeper8** [TopazTK/KH-ReFixed#28]
**Re:Fixed Version:**
_Enter in the version of Re:Fixed where the bug occurs [Ex. v0.75]_

2.10

**Game in Question:**
_Enter in the game where this is happening [Ex. Kingdom Hearts I]_

Kingdom Hearts II Final Mix

**Bug Description:**
_What is the bug like? What does it do? Etc. [Ex. Magic Sorting locks the Command Menu]_
Infinite Loading Screens

I cannot load my Save File and after starting a new game and watching one cutscene it never loads.

**Reproduction Steps:**
_Tell us, step by step, how to reproduce the bug._
Simply use one of the 1.0.1.X exes and try to load the game.
It does not happen with 1.0.0.X versions or the original exe so it is specically an issue with 1.0.1.X versions of Re:Fixed 2.10

**Comment by TopazTK** [comment]
This only happens if you are using an incompatible mod (Ex. Refight Sephiroth) or did not install the dependency patch correctly or at all.

Closing unless proven wrong on this.

**Comment by Cuddlecreeper8** [comment]
Other than your mod I am only using HD Textures Mod, HD Maps Mod and HD Environments and I installed the dependency patch by following the guide so I'll try reinstalling the mod for like the 4th time but I'm almost certain that the other mods I use are not the issue.

**Comment by TopazTK** [comment]
Re-opening, proven wrong on this.
Apparently a certain bug with the updater will cause the update dialog to not appear on fullscreen.
Will fix in v2.50. Sorry for the dismissal of this issue.

**Comment by TopazTK** [comment]
Fixed. I do not let the game start before the update check commences.
Will push ASAP. Closing.
