### ISSUE TITLE
[FEATURE REQUEST] Dual Audio on 358/2 | coded | 0.2 | Back Cover?

### ISSUE THREAD

**Issue by notjokr** [TopazTK/KH-ReFixed#29]
I am sure it is on the pipeline, but I was just asking to see how feasible this would be. It would be nice of ReFixed down the road was able to add full consistency across all titles in the collection as far as audio language options go

**Comment by TopazTK** [comment]
0.2 and Back Cover are not in the scope of Re:Fixed, as they are not considered legacy games.
358/2 and Re:Coded are all pre-rendered. It would be next to impossible to implement DA for them.

Requests rejected, closing.
