### ISSUE TITLE
[FEATURE REQUEST] Nvidia bug fix, Confirm button fix, Nintendo button layout

### ISSUE THREAD

**Issue by agufungus** [TopazTK/KH-ReFixed#30]
Hello, I just learned about this patch, and I would like to know if these features would be possible in a future update:

**Nvidia graphics bug fix**
I noticed a bug when playing in my RTX 3090 PC that some worlds have this texture bug. Sometimes this also happens when pausing, especially during the Gummi Ship stages. I've tried the game in an older PC with GTX 960, and none of the bugs happen. Not even official updates tried to fix this bug. So far I've noticed this in Kingdom Hearts Final Mix, as I haven't played the other games yet. Here's a sample of what's happening: https://imgur.com/a/J9oKxZG

**Confirm button fix**
As you know, there's the option in the game that lets you select which button to use as the Confirm button, either X/A or Circle/B. However this also results in the functions of said buttons being inverted in-game, with the Jump button becoming Attack, and vice versa. A fix to prevent this button inversion (for example, choose Circle/B as Confirm, and keep it as Jump at the same time) would be nice.

**Nintendo button layout**
So the options available in the game are PlayStation buttons and XBOX buttons. A nice addition would be a Nintendo button layout for those who use the Switch controller or other controllers that use the layout, like the 8bitdo controllers.

So far the current fixes and features are looking good. Keep it up!

**Comment by TopazTK** [comment]
> nVidia Graphics Bug Fix cannot be done unless I have that card to tinker the game with.

> You do know that function is working as intended, and reversing that defeats the whole purpose, right?

> I cannot easily do this without a patch, and I am not gonna make a second one without a huge feature to get behind, like Dual Audio.

Requests rejected, closing.

**Comment by Squall-Leonhart** [comment]
I've notified an nvidia QA contact about the issue, but you'll have to submit driver feedbackusing the form @ https://forms.gle/kJ9Bqcaicvjb82SdA
