### ISSUE TITLE
[BUG] Added Sound Effects Play at Maximum Volume Regardless of Selected Sound Volume

### ISSUE THREAD

**Issue by RelaxedBatter** [TopazTK/KH-ReFixed#31]
**Re:Fixed Version:**
v2.10

**Game in Question:**
Kingdom Hearts 1

**Bug Description:**
No matter the volume selected for Sound Effects or Master Volume, both the _auto-save_ sound effect and the _ability toggle_ sound effect (with the Reaction button) play as if both volumes were set to 10, even if the channel is muted by being set to 1.

**Reproduction Steps:**
Set Sound Effects volume or Master Volume to any value other than 10, then trigger an auto-save or toggle an ability on/off in the Abilities menu.

**Screenshots/Video:**
[Ability toggle](https://streamable.com/g92qyl) and [auto-save](https://streamable.com/3aesbq) examples.

**Comment by TopazTK** [comment]
To be fixed in v2.50 with a rewrite of the sound engine.
Will be closed upon release.

**Comment by TopazTK** [comment]
Fixed. Not released yet but still closing this.
