### ISSUE TITLE
[BUG] Auto saving stopped working in KH1

### ISSUE THREAD

**Issue by BParks21** [TopazTK/KH-ReFixed#32]
**Re:Fixed Version:**
Latest. 

**Game in Question:**
KH 1 latest epic version

**Bug Description:**
Auto saving stopped working. It was working fine when I first installed version v1.0.1.2. Then I wanted to reinstall the original .exe so I did to test something. After testing the original .exe I reinstalled v1.0.1.2 .exe and it stopped working. Everything else is working like the field of view mod, the soft reset and the others. Only auto save seems broken. I tried deleting the .dat file but that didn't fix it either. I also uninstalled the game and removed all files in the documents directory. Then I reinstalled the game and the mods and it still refuses to autosave. There is no file in slot 99. KH2 and BBS work fine. 

**Reproduction Steps:**
I have no idea.

**Comment by TopazTK** [comment]
Sometimes, save files get broken. This is a base game issue. Autosave refuses to write to them out of fear.
A fix for it will not actually come. The only thing you can do is to delete your save and make a new one. You should be able to transfer your saves with KHSaveEditor.

Sorry.

**Comment by BParks21** [comment]
> Sometimes, save files get broken. This is a base game issue. Autosave refuses to write to them out of fear. A fix for it will not actually come. The only thing you can do is to delete your save and make a new one. You should be able to transfer your saves with KHSaveEditor.
> 
> Sorry.

Ok thanks for the info. Quick question about the fov mod. Will it ever work with controller vibration? I noticed when enabled it disables the controller vibration. Seems to replace the vibration toggle in the config menu. I imgaine this is all intended. Sorry I know it's not relevant to the issue above.

**Comment by TopazTK** [comment]
> > Sometimes, save files get broken. This is a base game issue. Autosave refuses to write to them out of fear. A fix for it will not actually come. The only thing you can do is to delete your save and make a new one. You should be able to transfer your saves with KHSaveEditor.
> > Sorry.
> 
> Ok thanks for the info. Quick question about the fov mod. Will it ever work with controller vibration? I noticed when enabled it disables the controller vibration. Seems to replace the vibration toggle in the config menu. I imgaine this is all intended. Sorry I know it's not relevant to the issue above.

Yea, I hijack the vibration option. It will be made irrelevant soon as it will always be enabled.
