### ISSUE TITLE
[BUG?] resolution/anti aliasing bug?

### ISSUE THREAD

**Issue by g0mezu** [TopazTK/KH-ReFixed#33]
Re:Fixed Version: 2.10

Game in Question: Kingdom Hearts I

Bug Description: i think the game is not in my resolution, when i screenshot in fullscreen the screenshot appers with 800x600 and even in borderless the edges, edges of the characters are like if i don't have anti aliasing on, i dont know if there is a way I can force my resolution in the game

Reproduction Steps:  I installed the game, applied the refixed patch, tried to put it in fullscreen 1440x900 (my resolution) and saw that it was kind of weird, I kept switching between options and saw no difference

Screenshots/Video: https://imgur.com/a/mFaDpeY

**Comment by TopazTK** [comment]
Hmm, it gets squishy.
It should not do that, since my screen is ALSO 1440x900, and it was the very first resolution I have tested.
I will see this through and get back to ya.

**Comment by g0mezu** [comment]
so meanwhile i tested something, i reinstalled the game and opened without your mod and... same thing, its like a game bug because i did a little research and saw people on reddit with the very similar problem, the resolution is stuck at 800x600 etc. 

I dont found a solution, i took more screen shots, and there are some strange things like, when I put it in fullscreen and select my resolution the screenshot is at 800x600, in borderless in the settings the resolution appears "locked" at 800x600 BUT the screenshot is at 1440x900 but in-game it is strange as if it had been given a wrong upscale

here are the screenshots https://imgur.com/a/hp8GfkR

**Comment by g0mezu** [comment]
So... now that i found out that it's not a bug in your mod I think I'll have to play it like that anyway, because I don't know what to do, i didn't find anything if you find something that can help I'll be grateful

**Comment by TopazTK** [comment]
Yea, my fix is supposed to circumvent this.
Will look further.

**Comment by g0mezu** [comment]
Ok, if you want any logs or test anything, i will be grateful to help

**Comment by g0mezu** [comment]
I was wondering, can you tell me if the original game had any updates? because I'm using the pirated version for now before buying to test if it runs on my PC and I think it came without any update, did you test your Fix in the pirated version?

**Comment by TopazTK** [comment]
> I was wondering, can you tell me if the original game had any updates? because I'm using the pirated version for now before buying to test if it runs on my PC and I think it came without any update, did you test your Fix in the pirated version?

Re:Fixed supports any version, updated or not, pirated or not.

**Comment by g0mezu** [comment]
Got it

**Comment by g0mezu** [comment]
Hello again, i have new information, i don't know if it's relevant or not, but every time i change the game's resolution when it's in fullscreen my whole monitor is at 800x600 regardless of the resolution i choose, i used a second monitor to watch the windows resolution settings, if I try to give alt + tab to change in windows the game switches to window and the resolution goes back to 1440x900, and this happens in all games I hadn't tested the others before 

and I also saw that there's something wrong with the aspect ratio when it's borderless, if you notice the menu in the upper left corner, in borderless the "esc" is off the screen https://imgur.com/a/sHMHNJ5

so that's it, i think that's the most i could get of information

**Comment by TopazTK** [comment]
I mean that ESC is not accounted for, so it's normal for it to be like that.
Tagging as "Won't Fix" and closing until I can get more info out of it.
