### ISSUE TITLE
[BUG] [BBS] Rename Finish prompt appears in unrelated menus

### ISSUE THREAD

**Issue by RelaxedBatter** [TopazTK/KH-ReFixed#34]
**Re:Fixed Version:**
v2.10

**Game in Question:**
Birth by Sleep

**Bug Description:**
Pressing Triangle/F in certain menus will bring up the Rename Finish prompt, regardless of whether you're in the _Finish Command_ submenu or not. Upon pressing Submit or Cancel, the prompt will reappear immediately, often several times before it gives up after a seemingly random number of times (lowest recorded was 1 reappearance, highest was 5). The action assigned to Triangle/F still occurs, but the Rename Finish prompt pauses the game until an option is selected.

**Reproduction Steps:**
- Open the Pause menu, either in-world or on the World Map.
- Open any of the following menus: _Command Decks_, _Items_, _Abilities_, or _D-links_ (including any of these menus' submenus).
- Press Triangle/F while in any of these menus; the Rename Finisher prompt will show up. Submitting a name will change the Finish Command's name.

**Screenshots/Video:**
[Here's](https://imgur.com/ka36QVl) it happening on the _Items_ > _Equip_ menu.

**Comment by TopazTK** [comment]
Okaaaay this is odd. İ will look into this.

**Comment by TopazTK** [comment]
Fixed with v2.75.
Closing.
