### ISSUE TITLE
[BUG] Autosave not activating in KH2

### ISSUE THREAD

**Issue by Sefie1999AD** [TopazTK/KH-ReFixed#35]
**Re:Fixed Version:**
Release v2.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Autosave is not activated in the latest version of KH Re:Fixed when playing Kingdom Hearts II.

**Reproduction Steps:**
Load a save, and keep entering new rooms several times. The game does not overwrite the auto-save slot (99). The same happens with exe versions [v1.0.0.0] and [v1.0.0.2]. I can confirm that the Re:Fixed is otherwise working, since other features do work, e.g. having an option to skip Roxas' story, and using soft reset works normally.
**Other tests:** reverting to Re:Fixed 1.50 for KH2 makes the autosave activate on slot 99 whenever I reload a save, so old versions seem to be unaffected. Autosave seems to work normally in KH1 when using Re:Fixed 2.10.

**Comment by TopazTK** [comment]
Look at #32 for the answer.
