### ISSUE TITLE
[BUG] [FM] Game crashes when entering cid's shop

### ISSUE THREAD

**Issue by imsl0wer** [TopazTK/KH-ReFixed#37]
**Re:Fixed Version:**
2.10

**Game in Question:**
Kingdom Hearts Final Mix

**Bug Description:**
After the Pluto cutscene when entering Cid's shop the game crashes to desktop

**Comment by TopazTK** [comment]
Cannot reproduce this.
Please tell me more of your game state, a save may also help.

**Comment by imsl0wer** [comment]
Using proton-ge and steam to launch and play the game
and save is right here: https://file.io/96N8KihxzVh5
