### ISSUE TITLE
Add support back for Sirius902 LuaBackEnd fork

### ISSUE THREAD

**Issue by DuIslingr** [TopazTK/KH-ReFixed#38]
Can you please add this for convenience of use of being able to have both what this provides and be able to load other mod scripts via the back end. Particularly for use on the steam deck as this functions fine on it. Getting the games to run at all is already a chore right now so this would be appreciated without having to putz around figuring out how to get the front end working with it too.

**Comment by TopazTK** [comment]
This was an issue which Sirius needed to address, which he did.
If you look at 2d45d68d5fe271c220b36f4633c8889fe0eea839 you can see the check was removed.
Wait until v2.75.
Closing.
