### ISSUE TITLE
Game Crash to Desktop When Scrolling Abilities - 2.75

### ISSUE THREAD

**Issue by Abraxas000** [TopazTK/KH-ReFixed#39]
I just updated KH2 to 2.75 and now my game is crashing to desktop with no error codes when I'm scrolling through Sora's support abilities.

Steps for me to reproduce:

1. I just escorted Queen Minnie through the throne room (Critical Mode from the start)
2. Finished the cutscene after the throne room
3. Get the party change prompt
4. Go into the abilities to equip Sora's new ability
5. Scroll down into the support abilities
6. Once I get to a certain point going from the top down, or from the bottom up, the game crashes to desktop. (It seems to be Experience Boost that's causing the problem. If I go from either direction, as soon as it attempts to scroll from anything to Experience Boost, it crashes)

The .dmp file is showing as updated at the time of one of the crashes, but the .dmp file is empty.

Downgraded back to "Re-Fixed for 2FM-88-v2-11-1646837718" and was able to get through to save the game.  Updated back to 2.75, went back into the menu from the standard menu path and it crashed again when scrolling through Sora's support abilities.

I'm not speed runner and am primarily doing a nostalgia playthrough so I'll be staying on the old version.

Is there a way to not get prompted for updates so the startup process doesn't get interrupted?

**Comment by TopazTK** [comment]
Question -- Are you using Dual Audio by chance?

**Comment by Abraxas000** [comment]
I am not.

**Comment by TopazTK** [comment]
Fixed! Releasing an urgent update tagged v2.80.
Thanks for your report.
Closing.

**Comment by Abraxas000** [comment]
Confirmed, no longer able to reproduce and the exe is 7MB smaller. Great job and thank you much for the fast turnaround!
