### ISSUE TITLE
[BUG] Custom magic menu resets when retrying a forced encounter or loading a save

### ISSUE THREAD

**Issue by aichi-n-crew** [TopazTK/KH-ReFixed#44]
Re:Fixed Version: 2.90

Game in Question: Kingdom Hearts 2

Bug Description: Selecting retry in battles or forced encounters resets the custom magic selection you set it to. 

Reproduction Steps:
Set your magic to whatever custom format for the menu. 
begin a forced encounter or battle and lose it.
select retry
double check your magic menu and it will be reset

it also happens when you reload a save where you already had it customized, however i think that just cant be fixed

**Comment by TopazTK** [comment]
Thanks for the report! Investigating.

**Comment by TopazTK** [comment]
Investigation done! The error could not be replicated.
However, I will try to add in a way to save the costumization.

**Comment by TopazTK** [comment]
Closing for now as adding the customized menu to a save is tricky.
