### ISSUE TITLE
[BUG] Unable to exit through any game through its ESC menu

### ISSUE THREAD

**Issue by aichi-n-crew** [TopazTK/KH-ReFixed#47]
Re:Fixed Version: 2.90

Game in Question: All of patched ones

Bug Description: you're unable to close the game out through its ESC menu. selecting "end game" does nothing and keeps the game open

Reproduction Steps: just open any game normally through its launcher and press the ESC key after you either reach the title screen or are already playing throughout. the game will continue playing despite selecting "End game" at the end of the menu

its not a super big issue as i can just ALT+F4 but for those who dont like doing so might find this a bother.

**Comment by TopazTK** [comment]
Cannot be fixed as of now. But with the upcoming v3.00, the "BACK" option in the title screen was fixed at least.
Closing.
