### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HunterAhlquist** [TopazTK/KH-ReFixed#48]
**Re:Fixed Version:**
v2.90
 
**Game in Question:**
Kingdom Hearts I

**Bug Description:**
A large green artifact appears under Sora and his party members.

**Reproduction Steps:**
Not sure how to reproduce, it just kinda happens sometimes

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_
![image](https://user-images.githubusercontent.com/36090375/174465788-92d43592-510c-4430-863c-75ac83dd0447.png)

**Comment by TopazTK** [comment]
Not related to Re:Fixed. Closing.
