### ISSUE TITLE
[BUG] Enhanced FOV in KH1FM disables controller rumble.

### ISSUE THREAD

**Issue by BlueDragon992** [TopazTK/KH-ReFixed#54]
Reproducing it is rather simple. If you go into the config menu and set the FOV to classic, rumble is on. But when you set it to enhanced, it turns off.

I'm using a wired Xbox Series X controller (which should have the same functionality as a wired Xbox One or Xbox 360 controller) for reference.

**Comment by TopazTK** [comment]
Known issue. I hijack the vibration option to give the sense of illusion with these settings.
I will soon detach the vibration from these settings and make it an option on the config file.
Closing.
