### ISSUE TITLE
[BUG] Retry Feature Bug - KH2

### ISSUE THREAD

**Issue by Omnises** [TopazTK/KH-ReFixed#55]
**Re:Fixed Version:**
v2.90

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
The bug concerns the retry feature. In event fights, like bosses and storyline encounters (I have not observed this happen in other circumstances), some gameplay elements may not reset correctly.
For example, being in a drive form before dying and then retrying may have the drive form still active afterward with the same amount of drive remaining. This also occurs with summons. Another example is party members, whom if you switch during an encounter might stay after retrying, when the normal behavior is for the party to reset back to what it was. Furthermore, MP sometimes is not reset when recharging. Lastly, Items used may not return to having not been used. There may be other elements that don't reset that should that I have not noticed. 
HP, however, I suppose by nature of it needing to be depleted in order to retry, always goes to full as per usual.
It's worth mentioning that this bug does not have a permanent effect. Simply dying again and retrying will correctly reset these gameplay elements. (I've never observed this bug occurring twice in a row, and I'm not sure if it can). Thus, I would rate the devastation of the bug low, however, it's annoying if grinding a boss. That's all.
(is this a native KH2 bug that happens with continuing? I can't remember.)

**Reproduction Steps:**
Unfortunately I found no consistent way to reproduce the bug. However, simply doing a fight (Shan-Yu and Barbosa I had this occur in a few times), doing something like using a drive, and dying over and over again should have the bug occur, as those are the conditions I found it.

**Screenshots/Video:**
I could provide a video if requested. I'm not sure if it's overkill or not, and I don't want to spend the energy or disk space without the need to, y'know. lmk.

**Comment by Omnises** [comment]
My bad. I looked through the closed issues and I guess I missed them ;/

**Comment by TopazTK** [comment]
Should be completely fixed as of d8a8c063073dc15feddcd494038b1e772c5fbc4e.
Closing.
