### ISSUE TITLE
[BUG] EXIT Option not-functional.

### ISSUE THREAD

**Issue by supersnackbros** [TopazTK/KH-ReFixed#56]
**Re:Fixed Version:**
2.90

**Game in Question:**
Kingdom Hearts FM and Kingdom Hearts II FM

**Bug Description:**
Attempting to close the game via the Game Settings menu does not work, and returning to the game selection menu causes an infinite load screen.

**Reproduction Steps:**
Access game settings menu with escape key from either the title screen or the pause menu, then choose the option to quit game. Application will not close, but resume as it was.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
Fixed in v3.00.
Closing.
