### ISSUE TITLE
[BUG] KH2 Locking to 60 FPS based on camera angle?

### ISSUE THREAD

**Issue by BigheadSMZ** [TopazTK/KH-ReFixed#57]
**Re:Fixed Version:**
v2.90

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Depending on the camera angle, the FPS drops to 60. During cutscenes, the game drops to 60 FPS. I noticed this in Twilight Town playing with Roxas. 

**Reproduction Steps:**
Start a game with Roxas, the issue is immediately present based on the starting camera angle (drops to 60 FPS). Turn the camera to the left a bit, and it works fine. It's also happening in cutscenes with an unlocked framerate and all syncing methods disabled.

**Additional Info:**
So I read that this patch (ReFixed) is supposed to alleviate this issue, but it does not seem to work for me. It works so far in that I can skip the Roxas story, but no matter what combination of settings I use (framelimit on/off,120) or vsync on/off and gsync on/off, the game locks to 60 FPS when the camera is facing certain angles. The game is patched v1.0.0.8, the "ReFixed" patch has v1.0.0.2 in the executable name. Is that maybe why it is not working? Is there a version of this patch for v1.0.0.8?

Also, the patch provided here for v1.0.0.8 (ported by Explode) does seem to work, as there is no FPS drops to 60 when applied to the main executable:
https://www.reddit.com/r/KingdomHearts/comments/mhrug6/kh_15_25_pc_stuttering_fix_cutscene_framerate_fix/

So I could just use that, but then I would be missing out on all the other quality of life features of this patch.

**Comment by TopazTK** [comment]
Intentional. Game crashes otherwise.
It was fixed, but the fix was removed in v2.75 because of too many bugs. I guess the README update did not save.
Will not be fixed.
Closing.
