### ISSUE TITLE
Launcher executable not properly communicating with new REFIX executables[BUG] 

### ISSUE THREAD

**Issue by JakeTheJake74** [TopazTK/KH-ReFixed#60]
**Re:Fixed Version:**
v 2.90

**Game in Question:**
Kingdom Hearts 1, 2, and BBS

**Bug Description:**
I noticed an issue when trying to exit back from the titles with new executables to the main launcher. Basically, you have to manually close that game executable's window (not the one for the loading screen) as it seems to not communicate with the new executables properly. Once you do it'll load the launcher's exe back and close the loading screen exe. If you don't, the game will never close and so the loading screen never fades. This doesnt happen with game's that didnt have replaced executables.

**Reproduction Steps:**
If you launch the launcher (1.5+2.5.exe), select a game with a new exe (1,2,BBS), and click back in the main menu. It won't return to the launcher menu unless you manually close the game.

**Comment by TopazTK** [comment]
Fixed in v3.00. Wait for it's release. 
Closing.
