### ISSUE TITLE
[Request] Kingdom Hearts II Audio Bugs

### ISSUE THREAD

**Issue by CostPerUnit** [TopazTK/KH-ReFixed#61]
I've heard that a lot of the missing sound effects and sounds that don't always play are in the files but just don't work properly due to audio bugs. I'm unsure how true this is but it's currently the biggest issue affecting me in KH2 with or without the mod. I'm hoping you might be able to see if there's anything obvious that can be fixed.

Also, audio volume sometimes fluctuates as well but I'm unsure if this part is windows's fault or not so I put this as a footnote.

**Comment by CostPerUnit** [comment]
Duplicate. My apologies.

**Comment by TopazTK** [comment]
Duplicate of #18 and #9.
I am glad you figured this on your own, the answer given in those 2 are applicable here.
