### ISSUE TITLE
[REQUEST] Please add audio downmixing

### ISSUE THREAD

**Issue by Willow321Go** [TopazTK/KH-ReFixed#62]
The games when in combat often cause the audio on many systems to cutoff randomly when more than a couple of sounds occur at once. Please could you fix this? I believe this to be caused by a lack of sound mixing.

**Comment by HarryTVisitor** [comment]
Indeed, this is a very major issue especially when playing with headphones. It usually occurs whenever there's too many sounds going on behind the player as well.

**Comment by Willow321Go** [comment]
my audio outputs directly through hdmi now and it still does this, I don't
have a motherboard speaker so I don't know what to do.

**Comment by TopazTK** [comment]
Cannot fix at this moment. Closing.
