### ISSUE TITLE
[BUG] Can't Pause Game & Can't skip Roxas story

### ISSUE THREAD

**Issue by ZeXi0** [TopazTK/KH-ReFixed#63]
**Re:Fixed Version:**
v2.90

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Bug 1. Out of combat, I cannot access the menu, it just softlocks me, in that state I can pull up the PC menu, but can't quit. Bug 2. Picking Skip Roxas Story triggers an infinite loading screen after the opening cutscene.

**Reproduction Steps:**
_1. Pause the game out of combat as Roxas (have not tested with Sora yet). 2. Select Skip Roxas Story.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by ZeXi0** [comment]
I'm only on the 2nd Day of the prologue, so I'll continue to test until I beat Twilight Town.

**Comment by TopazTK** [comment]
The game was not patched properly. Please patch it again.

**Comment by ZeXi0** [comment]
Swapped back to OG EXE, and still had issues with pausing. Reinstalling the game.
