### ISSUE TITLE
Cannot beat Shan-Yun [BUG] 

### ISSUE THREAD

**Issue by Donobland** [TopazTK/KH-ReFixed#64]
**Re:Fixed Version:**
 v2.90

**Game in Question:**
Kingdom Hearts 2.5

**Bug Description:**
Upon killing Shan-Yun in the first bossfight in Mulans world, I am immediately loaded straight into the fight again as if I hit "retry" however I am not healed and my drive gauge remains where it was when I completed the fight. There is seemingly no way around it.

**Reproduction Steps:**
Simply killing Shan-Yun on critical difficulty. Exiting the game, repairing game files, task managing it, etc. doesnt seem to affect it,
I have been unable to progress past this point in the game as usual.

**Screenshots/Video:**
(dont have a video rn but I can provide one later if necessary)

**Comment by aichi-n-crew** [comment]
its a known issue if youre using the mod. have you tried uninstalling it and playing it vanilla so that way you can avoid this section?

**Comment by Donobland** [comment]
Ahh my bad just got this mod. And I havent had time to try that but I will. Are their any other instances like this or is it just the Shan-Yun boss?

**Comment by TopazTK** [comment]
Known issue as stated in #43 and #51. Was already fixed in the upcoming v3.00 release.
Do not use Mickey.
Closing issue.
