### ISSUE TITLE
[BUG] Roxas' Story is unplayable in v2.90

### ISSUE THREAD

**Issue by anim0sityyy** [TopazTK/KH-ReFixed#65]
**Re:Fixed Version: v2.90**

**Game in Question:**
Kingdom Hearts 2

**Bug Description:**
When choosing to play Roxas' Story rather than skip it, and you get to the part where you must select the Staff, Sword, or Shield in his mind space, after making your selection, the game treats it as if you chose to skip Roxas' Story, and boots you into Sora, except instead of wielding the Kingdom Key, he has the chosen Struggle Weapon.

**Reproduction Steps:**
My steps were:
1. Start New Game
2. Select Yes to Play Roxas' Story
3. Select Critical Difficulty
4. Switch Audio Language to Japanese as soon as Config is accessible when paused
5. Save game in hideout, reload game, then load save
6. Complete the first wave of jobs then talk to Hayner
7. After cutscenes, select between Sword, Shield, and Staff, I chose Shield.
8. Watch your selection turn into the Kingdom Key, then game transitions immediately to the Sora waking up cutscene, and boots you outside the mansion with your Struggle Weapon instead of the Kingdom Key, and English Audio Language selected again in Config.

**Comment by TopazTK** [comment]
I cannot for the life of me replicate this. But it is such a common issue for some reason. Should be fixed in v3.00 hopefully.

**Comment by TopazTK** [comment]
Could not be reproduced with v3.00 as of today. Closing.
