### ISSUE TITLE
[REQUEST] Hidden Form Items

### ISSUE THREAD

**Issue by gledson999** [TopazTK/KH-ReFixed#66]
I don't know if you know, but crazycatz00 in his patch allows Form items visible, is it possible to do this in KH2FM from Epic Re: Fixed?

**Comment by TopazTK** [comment]
Now, I would need to patch images for Final Form.

But something I am planning on introducing in v3.00 may allow me to do this seamlessly. So...

**Comment by gledson999** [comment]
Nice, If you want, I can help with the image, I believe it's some flag inside the exe that allows you to do this kind of thing.

Do you know what address has this in exe?

**Comment by TopazTK** [comment]
No need. I know how to attach images to items, being the second ever person to figure out how 03system/item works.
As for them being hidden, that is indeed the case. But no matter, everything is moddable if you try hard enough.

**Comment by TopazTK** [comment]
Concept crafted, perhaps the jankiest ASM Hack I had to do.
To be featured in v3.00.

![image](https://user-images.githubusercontent.com/95656963/181904939-77c472e2-dd9d-4953-9bee-55d1d289b358.png)

Closing.

**Comment by TopazTK** [comment]
4b4b1a2dd5bb5a256d2361ba6218c8136eeeeaf4
