### ISSUE TITLE
[BUG] Missing Maps when skipping Roxas' Story

### ISSUE THREAD

**Issue by MOSTROPOLIS** [TopazTK/KH-ReFixed#67]
Re:Fixed Version: 2.9

Game in Question: Kingdom Hearts 2

Bug Description: I started a new game and chose to skip Roxas's segment. I was also going for all achievements. I have filled everything out in Jiminy's journal but I am missing 2 maps. I am guessing they are from Roxas's section? If not, I am sorry for being dumb haha.  

Reproduction Steps: Chose start new game, Chose skip Roxas segment, played normally until beaten

Screenshots/Video:
![Missing Maps](https://user-images.githubusercontent.com/110146211/181413295-b9aeec82-aa47-46d9-9340-ad02096870ab.png)

**Comment by TopazTK** [comment]
Ah, fuck, right.

**Comment by TopazTK** [comment]
Fixed as of 317e12e92665ce58c6e4a0ff8ec4c4a9aac3168b.
Closing.
