### ISSUE TITLE
Can't quit game or go back to launcher 

### ISSUE THREAD

**Issue by BParks21** [TopazTK/KH-ReFixed#70]
**Re:Fixed Version:**
2.90

**Game in Question:**
KH1, KH2, BBS

**Bug Description:**
When I'm running anyone of these games and hit esc and try to quit the game the game does nothing and does not quit. It just continues to run as if I pressed nothing. If I use the soft reset and go back to the title screen and try to select back it won't return to the launcher it just sits on a black loading screen. Wasn't an issue in older versions. 

**Reproduction Steps:**
Launch any of the 3 games and try to quit one of the two ways.

**Screenshots/Video:**

**Comment by TopazTK** [comment]
Known. Fixed in v3.00. Closing.

**Comment by BParks21** [comment]
> Known. Fixed in v3.00. Closing.

I look forward to the new version!

**Comment by TopazTK** [comment]
> > Known. Fixed in v3.00. Closing.
> 
> I look forward to the new version!

Just to note: the ESC One is not fixed. The title screen one is.

**Comment by BParks21** [comment]
> > > Known. Fixed in v3.00. Closing.
> > 
> > 
> > I look forward to the new version!
> 
> Just to note: the ESC One is not fixed. The title screen one is.

Ahhh so the esc one won't be fixed until the next release?

**Comment by TopazTK** [comment]
> > > > Known. Fixed in v3.00. Closing.
> > > 
> > > 
> > > I look forward to the new version!
> > 
> > 
> > Just to note: the ESC One is not fixed. The title screen one is.
> 
> Ahhh so the esc one won't be fixed until the next release?

ESC One will never be fixed because SE programmed it stupid.

**Comment by BParks21** [comment]
Didn't it work with older versions of the mods I thought?

**Comment by TopazTK** [comment]
> Didn't it work with older versions of the mods I thought?

You see, I had to fix shutdown crashing the games and that broke the quit options.
I did fix the title screen one back but not the ESC one.
If you ask me whether to have ESC work or shutdowns not crash, I chose the latter.

**Comment by BParks21** [comment]
I see

**Comment by BParks21** [comment]
@TopazTK Yeah I'm still having issues in v3.00 quitting bbs when attempting to go back to the launcher, I tried doing it from a save point and a soft reset. It always freezes trying to go back to the launcher so it's really annoying trying to quit the game. The other titles seem to be working fine with both methods.

**Comment by BParks21** [comment]
> @TopazTK Yeah I'm still having issues in v3.00 quitting bbs when attempting to go back to the launcher, I tried doing it from a save point and a soft reset. It always freezes trying to go back to the launcher so it's really annoying trying to quit the game. The other titles seem to be working fine with both methods. Neverminded same issue with ddd. Also I'm hearing the auto save sound in ddd but no auto save is being made.

**Comment by TopazTK** [comment]
> @TopazTK Yeah I'm still having issues in v3.00 quitting bbs when attempting to go back to the launcher, I tried doing it from a save point and a soft reset. It always freezes trying to go back to the launcher so it's really annoying trying to quit the game. The other titles seem to be working fine with both methods. Neverminded same issue with ddd. Also I'm hearing the auto save sound in ddd but no auto save is being made. Yeah ddd auto save feature seems broken. I hear the sound eventually it creates a slot but it doesn't update the time played or any changes that have occurred during my progress. I've deleted my save file and config multiple times so it's not a corruption thing with my save.

BBS is still borked and I am trying to fix it. Autosave will only work with a save in it.
DDD Autosave will only show upon a soft or a hard reset because it is stupid.
You can find all this info in the Discord. However,
If you are getting frustrated: The only advice I can give you is not to use Re:Fined.

**Comment by BParks21** [comment]
Thought I was doing something wrong on my end that's why. So quitting to the launcher in BBS and DDD is not working correctly? Dang. Alright I'll check out the discord. Thank you.
