### ISSUE TITLE
[BUG] [KH2] Data Organization Bug 

### ISSUE THREAD

**Issue by shades7S** [TopazTK/KH-ReFixed#71]
**Re:Fixed Version:**
v2.90

**Game in Question:**
Kingdom Hearts II Final Mix

**Bug Description:**
Some data organization portals don't spawn/appear when you enter in the garden of assemblage and interact with the computer

**Reproduction Steps:**
You enter the garden of assemblage  after you finish the cavern of remembrance, you interact with the computer and then some data battle portals don't show up like they should do

**Screenshots/Video:**

![KH2FM Issue](https://user-images.githubusercontent.com/110640033/182968833-9c193b06-b065-4c09-a2e4-3c33e6d7e14e.png)

![KH2FM Issue []((2)](https://user-images.githubusercontent.com/110640033/182968892-7fdf4198-1dc2-4c51-918c-157605809c6b.png))
https://drive.google.com/file/d/1uYeeizJ8PE-2-upfS5o9IBg8rWCZszU2/view?usp=sharing   <-- First Video
https://drive.google.com/file/d/1yemsn42nXAdwvUuc3T66btWxR2qxtd1m/view?usp=sharing     <--Second Video

**Comment by shades7S** [comment]
nevermind it  fixed itself alone lol. sorry for the bother.

**Comment by TopazTK** [comment]
You have to beat the AS versions first.
Please pay attention to the game before making an issue.
