### ISSUE TITLE
[BUG]  Command Board crashing

### ISSUE THREAD

**Issue by RaptorTim** [TopazTK/KH-ReFixed#72]
**Re:Fixed Version:**
2.90

**Game in Question:**
_KINGDOM HEARTS Birth by Sleep FINAL MIX_

**Bug Description:**
Whenever you go into the Command Board, it loads a little, then just CTD, happens on both executables 

**Reproduction Steps:**
_Just go into Command Board

**Comment by HmmpHmmp** [comment]
Same exact thing is happening to me. I got rid of ReFixed and it wasn't happening again. I can confirm it is a ReFixed issue.

**Comment by TopazTK** [comment]
Known. To be fixed in v3.00.
Closing.
