### ISSUE TITLE
[BUG/OVERSIGHT?] Skipping Roxas's story prevents Journal Completion

### ISSUE THREAD

**Issue by TMKDash** [TopazTK/KH-ReFixed#73]
**Re:Fixed Version:**
_2.90_

**Game in Question:**
_Kingdom Hearts II_

**Bug Description:**
_If you start a save file by skipping Roxas's story, you never receive the Twilight Town or Mansion maps, both of which are acquired through cutscene and, to my knowledge, cannot be reacquired afterward since they automatically transfer to Sora. If you skip Roxas's story, that save file is permanently locked out of Journal completion. Naminé's Sketches can also be missed this way, but you use them a few rooms later and as far as I'm aware, they do not contribute to Jiminy's Journal completion._

**Screenshots/Video:**
![KINGDOM_HEARTS_II_FINAL_MIX_yV0gyeCbHo](https://user-images.githubusercontent.com/96037671/183569117-6e4d077b-75d3-4630-82b5-770b1b4640a9.png)

**Comment by TopazTK** [comment]
Please look at the closed issues before you pos.
This was fixed yesterday.
Closing.

**Comment by TMKDash** [comment]
Literally mulled over the list before posting and must've missed it, sorry for the trouble!
