### ISSUE TITLE
[BUG] Command Board/Mirage Arena crash

### ISSUE THREAD

**Issue by sinopias** [TopazTK/KH-ReFixed#78]
**Re:Fixed Version:**
v 2.90

**Game in Question:**
Birth By Sleep

**Bug Description:**
Game crashes if the Command Board is opened. Same if you try to enter the Mirage Arena.

**Reproduction Steps:**
Proud Mode. Terra story.
The Command Board crash happens whether I open it through the menu in the overworld or inside a world.
I replaced the Re:Fixed .exe file with the original one and the Command Board opened up without a problem.

**Comment by TopazTK** [comment]
Addressed in v3.00.
Closed.
