### ISSUE TITLE
[Feature Request] Make Soft Reset combo on par with PSP Birth by Sleep

### ISSUE THREAD

**Issue by AkiraJkr** [TopazTK/KH-ReFixed#8]
Basically the title. I feel like having that R1+L1+Select+Start combo would be far more fitting and familiar than the current one, plus, it would avoid incompatibilities with other software, like some overlays you can pull with that:

High Quality Ver: https://cdn.discordapp.com/attachments/778539700981071875/945712668348653588/2022-02-22_12-58-43.mp4

https://user-images.githubusercontent.com/27028529/155174964-0aa6db56-e1ce-4847-b43f-c0dc223d667d.mp4

(

**Comment by TopazTK** [comment]
I decided to use START+SELECT on all games because that's what Soulcalibur 3 uses, and it allows for people with many different keyboards to take advantage of it. However, considering the problems it may cause, I will add it to the list.

**Comment by TopazTK** [comment]
The issue has been addressed from commits dd1da9fdd052aa618a531423f4cbbee2e4bf8eea through 9433343e308e9e5b5222e393bd56636f5372d578.
Closed.
