### ISSUE TITLE
[KH2] Audio Issues (Missing SFX/Quotes)

### ISSUE THREAD

**Issue by TheSoraHD** [TopazTK/KH-ReFixed#9]
Has been happening since the PS3 version, every HD release is affected. Easiest way to reproduce this is to spam Sora's combo (if you go slowly attacking, you can hear more quotes) or just starting Jafar's battle. The files are there and can be heard with external tools, it's the game fault for not reproducing them.

Bizkit047 has this problem documented on YT:

https://www.youtube.com/watch?v=zaMcGIJiWVM

**Comment by TopazTK** [comment]
This is not something that I can really work with, since the audio engine resides on the C++ side rather than the C# side.
I am a modder and not a magician. But I am planning to look into it with Ghidra.
Leaving this issue open, but tagging it as "Can't Fix" for now.

**Comment by TopazTK** [comment]
Closing this for now. May reopen if I *can* fix it.
